#ifndef _FRAMEWORK_GRAPHICSDX12_COMMONCONSTANT_H_
#define _FRAMEWORK_GRAPHICSDX12_COMMONCONSTANT_H_

namespace Framework::GraphicsDX12
{

    constexpr UInt32 OUTPUT_RTV_NUMBER{ 2 };

    constexpr UInt32 RESOURCE_RTV_COMMONDESCRIPTORHEAP_CAPACITY{ 1024 };

}

#endif